### PR TITLE
Add travis-ci and coveralls scripts.  Clean up some other build config stuff.

### PR DESCRIPTION
**Pull request by gfr10598**
This tweaks cmake file and install-protobufs, and adds .travis.yml to add basic travis-ci integration and coverage push to coveralls.

Also cleans up some related install-protobufs.sh, and CMake, README stuff.

Still need to work out some issues with clang, but its working with gcc, so that is good enough to get started.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/tcpinfo_lib/8)

### CODE REVIEW

**Comment by pboothe** [comment]
_[.travis.yml, line 49 at r1](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/8#-KW-gWFDEuALG9nFtNQb:-KW-gWFDEuALG9nFtNQc:b66du79) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/09325768f99a1413a5033ebc85ec41b0a7431385/.travis.yml#L49)):_

> ``` YAML
> before_script:
> # Check if protobuf compiler is present, and load if it is not.
> - sudo ./install-protobuf.sh
> ```

Why isn't `apt-get install protobuf-compiler protobuf-c-compiler libprotobuf-c0-dev libprotobuf-dev` sufficient? Why does it need to be installed from source? I am sure there is a reason, but a comment either here or in the README would be nice.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/8)_

**Comment by pboothe** [comment]
_[.travis.yml, line 27 at r1](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/8#-KW-k60PZp2ZKllRsVXn:-KW-k60PZp2ZKllRsVXo:byovzk1) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/09325768f99a1413a5033ebc85ec41b0a7431385/.travis.yml#L27)):_

> ``` YAML
> # TODO(gfr) See if there is a faster way to install these...
> - sudo apt-get -qq install libgtest-dev
> - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
> ```

Aha! It is preferred that you do this because the vagaries of the C++ and C build processes mean that gmock and gtest need the _exact same_ compiler flags that you are using for the rest of the program. Therefore, building from source is the responsible thing to do if you ever plan on using any compiler flags.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/8)_

**Comment by pboothe** [comment]
:lgtm: with one question and one "Aha!" moment.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/8#-:-KW-kcLjkf8mDbCLcpKS:b-2efse9)_

**Comment by gfr10598** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

_[.travis.yml, line 49 at r1](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/8#-KW-gWFDEuALG9nFtNQb:-KW04daKsuBKCOEZCJ_4:bkdo9l5) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/09325768f99a1413a5033ebc85ec41b0a7431385/.travis.yml#L49)):_
<details><summary>

<i>Previously, pboothe (Peter Boothe) wrote…</i></summary>



> Why isn't `apt-get install protobuf-compiler protobuf-c-compiler libprotobuf-c0-dev libprotobuf-dev` sufficient? Why does it need to be installed from source? I am sure there is a reason, but a comment either here or in the README would be nice.
> </details>
> Added comment in install-protobuf.sh.  It is recommended in the google protobuf documentation.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/8)_

**Comment by gfr10598** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

_[.travis.yml, line 27 at r1](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/8#-KW-k60PZp2ZKllRsVXn:-KW04tPH8l-dGfhDEKtQ:bb6sh2i) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/09325768f99a1413a5033ebc85ec41b0a7431385/.travis.yml#L27)):_
<details><summary>

<i>Previously, pboothe (Peter Boothe) wrote…</i></summary>



> Aha! It is preferred that you do this because the vagaries of the C++ and C build processes mean that gmock and gtest need the _exact same_ compiler flags that you are using for the rest of the program. Therefore, building from source is the responsible thing to do if you ever plan on using any compiler flags.
> </details>
> Ack.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/8)_

**Comment by pboothe** [comment]
Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/8)_

**Review by pboothe — APPROVED** [review]
Copy of LGTM from Reviewable.

**Pull request merged**
