### PR TITLE
Various code cleanup and small enhancements.

### PR DESCRIPTION
**Pull request by gfr10598**
Pass both old and new state to visitors.
Add partial implementation for PollOnce.
Add OnNewState to poller.
Add name annotations to TCPState values.
Improve comments.
Improve test coverage.
Small tweaks to cmake file.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/tcpinfo_lib/11)

### CODE REVIEW

**Comment by pboothe** [comment]
I thought this was integrated with coverage.io?

**Comment by gfr10598** [comment]
Huh.  Seems I can't respond to you comment.
Not sure what you mean.  It is integrated with coveralls.io, which is generally easiest to reach from the badge in the README.md.

**Comment by pboothe** [comment]
Right, but for example when I submit a new PR to https://github.com/m-lab/scraper , Coveralls updates the pull request to let me know how the test coverage levels will change with this PR. This doesn't seem to happen here?

**Comment by gfr10598** [comment]
Changed badges to use m-lab instead of gfr10598.  Looks like I also had a problem because I was using a repo_token for coverage, and hadn't set one up for m-lab repo.  I've just removed the token, as it isn't needed for public repos.

**Comment by pboothe** [comment]
_[src/connection_cache.h, line 44 at r4](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/11#-KWdORWrglOemtFTuE3z:-KWdORWrglOemtFTuE4-:bnsx8vc) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/003adb03a236b604fdc683bbf7121d87d9865f5a/src/connection_cache.h#L44)):_

> ``` objc
>     int round;
>     int protocol;
>     std::string msg;
> ```

Comment me! Hardly a string at all!

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/11)_

**Comment by pboothe** [comment]
_[src/tcpinfo.proto, line 80 at r4](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/11#-KWdPiqXSOycCsviYg4E:-KWdPiqXSOycCsviYg4F:b-83sjoh) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/003adb03a236b604fdc683bbf7121d87d9865f5a/src/tcpinfo.proto#L80)):_

> ``` protobuf
>   LAST_ACK = 9 [(name)="LastAck"];
>   LISTEN = 10 [(name)="Listen"];
>   CLOSING = 11 [(name)="Closing"];
> ```

Nice!

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/11)_

**Comment by pboothe** [comment]
_[src/tcpinfo_lib.cc, line 93 at r4](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/11#-KWdReHt1J_9om2SGO7o:-KWdReHt1J_9om2SGO7p:bb6zqqo) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/003adb03a236b604fdc683bbf7121d87d9865f5a/src/tcpinfo_lib.cc#L93)):_

> ``` cpp
>     break;
>   case InetDiagMsgProto_AddressFamily_AF_UNSPEC:
>     // We don't know how to interpret the addresses, so leave them unset.
> ```

Log?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/11)_

**Comment by pboothe** [comment]
Reviewed 2 of 9 files at r1, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: 4 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/11)_

**Comment by pboothe** [comment]
Overall comment: If we don't want to have the License comment bleed into the normal comments, can we give cool ascii art to the license comment and leave the normal comments as just // ?

If we are to believe Code Complete, reformatting things like 

```
/*****************
 * This is a comment.
 *****************/
```

represents a small but real mental burden on programmers and causes a non-zero slowdown when people want to update the comments.

**Comment by gfr10598** [comment]
I agree with Code Complete.  I try to use these "banners" only when I want something to pop out, i.e., be more noticeable and easier to find.  For those cases, I think it is worth the extra effort.
I think we actually want the copyright to be background noise, and the file banner to pop out.  Does this make sense?

---

Review status: 4 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

_[src/connection_cache.h, line 44 at r4](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/11#-KWdORWrglOemtFTuE3z:-KWdhg2DlVCN0BIqxCBV:bs7wumx) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/003adb03a236b604fdc683bbf7121d87d9865f5a/src/connection_cache.h#L44)):_
<details><summary>

<i>Previously, pboothe (Peter Boothe) wrote…</i></summary>



> Comment me! Hardly a string at all!
> </details>
> Done. 

---

_[src/tcpinfo_lib.cc, line 93 at r4](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/11#-KWdReHt1J_9om2SGO7o:-KWdhkXqvTiX3dL806qe:b-rzktay) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/003adb03a236b604fdc683bbf7121d87d9865f5a/src/tcpinfo_lib.cc#L93)):_
<details><summary>

<i>Previously, pboothe (Peter Boothe) wrote…</i></summary>



> Log?
> </details>
> Adding todo.  Don't have the desired logging infra yet.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/11#-:-KWdh7cdUyN47GaSg0-k:bp8dxkj)_

**Comment by gfr10598** [comment]
PTAL.  (just pushed upstream)

**Comment by pboothe** [comment]
_[src/connection_cache.h, line 55 at r5](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/11#-KWdloVnKp-BKOSpBbWX:-KWdloVnKp-BKOSpBbWY:b7vzyx6) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/e666f1362a38687cfb920d6bed6b9afe4924de5b/src/connection_cache.h#L55)):_

> ``` objc
>   bool UpdateRecord(size_t key, int protocol, std::string* data);
> 
>   // Compute key from socket <id>, and call UpdateRecord on non-local
> ```

backticks

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/11)_

**Comment by pboothe** [comment]
LGTM, but do please update comments as noted.

---

Review status: 4 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

_[src/connection_cache.cc, line 45 at r5](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/11#-KWdnLrQl6LATib0mZVQ:-KWdnLrQl6LATib0mZVR:b5z20nz) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/e666f1362a38687cfb920d6bed6b9afe4924de5b/src/connection_cache.cc#L45)):_

> ``` cpp
>     // and compute various stats, e.g. min rtt.
>     if (it->second.round == round_) {
>       static int count = 20;
> ```

Why 20? Why a static int? So many questions from one line...

Please add a comment that this is to only log the first 20 instances of this problem.

---

_[src/tcpinfo_proto_test.cc, line 397 at r5](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/11#-KWdnfyezh6GW8X8WVoH:-KWdnfyf0zTkfX_DRx8b:b-hgxqbp) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/e666f1362a38687cfb920d6bed6b9afe4924de5b/src/tcpinfo_proto_test.cc#L397)):_

> ``` cpp
>     "\xc0\xda\x00\x00\x80\x70\x00\x00\x00\x00\x00\x00\x0a\x00\x04\x00"
>     "\x63\x75\x62\x69\x63\x00\x00\x00", 0x110);
> // 001000
> ```

I don't understand this comment.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/11#-:-KWdoOVCX4ny_Zn7GWBn:b-2vkad4)_

**Comment by pboothe** [comment]
:lgtm: Now with a cool stamp.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/11#-:-KWdoUSy2pJrIgitWHyQ:bjiwmyq)_

**Comment by gfr10598** [comment]
Review status: 4 of 10 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

_[src/connection_cache.cc, line 45 at r5](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/11#-KWdnLrQl6LATib0mZVQ:-KWdthu9mkg4kizNowAp:bmcv7c) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/e666f1362a38687cfb920d6bed6b9afe4924de5b/src/connection_cache.cc#L45)):_
<details><summary>

<i>Previously, pboothe (Peter Boothe) wrote…</i></summary>



> Why 20? Why a static int? So many questions from one line...
> 
> Please add a comment that this is to only log the first 20 instances of this problem.
> </details>
> Added a TODO which should make it clear.

---

_[src/connection_cache.h, line 55 at r5](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/11#-KWdloVnKp-BKOSpBbWX:-KWdtVaVaAdUMjDMuM52:b-gd7zme) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/e666f1362a38687cfb920d6bed6b9afe4924de5b/src/connection_cache.h#L55)):_
<details><summary>

<i>Previously, pboothe (Peter Boothe) wrote…</i></summary>



> backticks
> </details>
> Already done in next PR, so leaving it til then.

---

_[src/tcpinfo_proto_test.cc, line 397 at r5](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/11#-KWdnfyezh6GW8X8WVoH:-KWdtbTIgukxUFVfUQz1:b20xaav) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/e666f1362a38687cfb920d6bed6b9afe4924de5b/src/tcpinfo_proto_test.cc#L397)):_
<details><summary>

<i>Previously, pboothe (Peter Boothe) wrote…</i></summary>



> I don't understand this comment.
> </details>
> Removed.  It was a note to myself.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/11)_

**Pull request merged**
