### PR TITLE
Large PR - Adapter to C code, demo polling implementation

### PR DESCRIPTION
**Pull request by gfr10598**
This one has a lot of content, some of it pretty ugly.  If you have suggestions for breaking it out into smaller PRs, happy to do so.
I suspect there will be places where I should improve the comments, since I've been pecking at this for about 6 weeks, so parts of it are just in my subconscious now.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/tcpinfo_lib/15)

### CODE REVIEW

**Comment by pboothe** [comment]
_[src/README.md, line 6 at r1](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15#-KWmy4NkM0QqyqmQT_wb:-KWmy4NkM0QqyqmQT_wc:bz3gwq6) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/a447e1c604896b7794abc638658b94228121b229/src/README.md#L6)):_

> ``` Markdown
> 
> ## tcpinfo_lib
> ... contains the primary interface for interacting with the
> ```

you are either leaving me hanging or being too clever

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15)_

**Comment by pboothe** [comment]
_[src/tcpinfo_proto_test.cc, line 534 at r1](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15#-KWmydWFh-PFaPbRgXz1:-KWmydWFh-PFaPbRgXz2:b-sgpst) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/a447e1c604896b7794abc638658b94228121b229/src/tcpinfo_proto_test.cc#L534)):_

> ``` cpp
> using namespace std::placeholders;
> 
> #define POLL_WITHOUT_FETCH(poller) \
> ```

Couldn't this be a method?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15)_

**Comment by pboothe** [comment]
_[src/tcpinfo_lib_test.cc, line 20 at r1](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15#-KWmymQkHfTB9KHov_G5:-KWmymQkHfTB9KHov_G6:b-v1yixt) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/a447e1c604896b7794abc638658b94228121b229/src/tcpinfo_lib_test.cc#L20)):_

> ``` cpp
> #include "connection_cache.h"
> // TODO(gfr) The include order matters.  If tcpinfo_lib.h is included later,
> // we get obscure compiler errors processing tcpinfo.pb.h.
> ```

:(

This is pretty bad. How hard is it to fix?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15)_

**Comment by pboothe** [comment]
_[src/tcpinfo_lib.cc, line 443 at r1](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15#-KWmzSlfgFuCmRo-kpX8:-KWmzSlfgFuCmRo-kpX9:bav245r) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/a447e1c604896b7794abc638658b94228121b229/src/tcpinfo_lib.cc#L443)):_

> ``` cpp
>   auto *diag_arg = (struct inet_diag_arg *)arg;
>   auto *msg = (struct inet_diag_msg *)NLMSG_DATA(nlh);
>   // This has to be tied to a specific instance of the TCPInfoPoller. 8-(
> ```

:(

Maybe lambdas can help?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15)_

**Comment by pboothe** [comment]
_[src/tcpinfo_lib.cc, line 443 at r1](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15#-KWmzSlfgFuCmRo-kpX8:-KWn-jacaRYMDxFKWdxa:b-cu7ed6) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/a447e1c604896b7794abc638658b94228121b229/src/tcpinfo_lib.cc#L443)):_
<details><summary>

<i>Previously, pboothe (Peter Boothe) wrote…</i></summary>



> :(
> 
> Maybe lambdas can help?
> </details>
> Looking into it more: probably not :(

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15)_

**Comment by pboothe** [comment]
_[src/main.cc, line 70 at r1](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15#-KWn0_MMr0gj3BI388ez:-KWn0_MNO3L5wNWz-Snk:b-d1j55g) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/a447e1c604896b7794abc638658b94228121b229/src/main.cc#L70)):_

> ``` cpp
> void on_new_state(int protocol, const std::string& old_msg,
>                   const std::string& new_msg) {
>   // Always output old data when we see new state!
> ```

This comment doesn't match the code?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15)_

**Comment by pboothe** [comment]
_[src/main.cc, line 20 at r1](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15#-KWn0x4C-Oq4prjaY78C:-KWn0x4C-Oq4prjaY78D:b-westa) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/a447e1c604896b7794abc638658b94228121b229/src/main.cc#L20)):_

> ``` cpp
> void DumpNlMsg(const std::string& nlmsg) {
>   std::ofstream out;
>   out.open("nldata", std::ofstream::app | std::ofstream::binary);
> ```

We're in agreement that hardcoding filenames is bad, right? And only okay in the context of a demo application?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15)_

**Comment by pboothe** [comment]
_[src/tcpinfo_c_adapter.c, line 72 at r1](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15#-KWn169D1ba-XMpZaSny:-KWn169D1ba-XMpZaSnz:b3kre) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/a447e1c604896b7794abc638658b94228121b229/src/tcpinfo_c_adapter.c#L72)):_

> ``` C
>   req.r.sdiag_protocol = protocol;
>   req.r.idiag_states = 1 << SS_ESTABLISHED;
>   // DO NOT SUBMIT
> ```

?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15)_

**Comment by pboothe** [comment]
_[src/tcpinfo_c_adapter.c, line 46 at r1](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15#-KWn1cpmE0k9DYS2IRjB:-KWn1cpmE0k9DYS2IRjC:b-xtgwk8) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/a447e1c604896b7794abc638658b94228121b229/src/tcpinfo_c_adapter.c#L46)):_

> ``` C
> };
> 
> #define MAGIC_SEQ 123456
> ```

Please make this a random number. 123456 is, imo, a worryingly probable input.  Or, put another way: https://vine.co/v/hl7Zpzh1979

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15)_

**Comment by pboothe** [comment]
Reviewed 1 of 10 files at r1.
Review status: 1 of 10 files reviewed at latest revision, 8 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15)_

**Comment by gfr10598** [comment]
Review status: 1 of 10 files reviewed at latest revision, 8 unresolved discussions.

---

_[src/main.cc, line 20 at r1](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15#-KWn0x4C-Oq4prjaY78C:-KWnCJUt7D-rh8MwDQ4A:b-7xixap) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/a447e1c604896b7794abc638658b94228121b229/src/main.cc#L20)):_
<details><summary>

<i>Previously, pboothe (Peter Boothe) wrote…</i></summary>



> We're in agreement that hardcoding filenames is bad, right? And only okay in the context of a demo application?
> </details>
> Yup!!

---

_[src/main.cc, line 70 at r1](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15#-KWn0_MMr0gj3BI388ez:-KWnCza9yJNl_nMe3cjL:b-896fix) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/a447e1c604896b7794abc638658b94228121b229/src/main.cc#L70)):_
<details><summary>

<i>Previously, pboothe (Peter Boothe) wrote…</i></summary>



> This comment doesn't match the code?
> </details>
> Done.

---

_[src/README.md, line 6 at r1](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15#-KWmy4NkM0QqyqmQT_wb:-KWnD-ogJixGEPiQUOFh:b4jzz4o) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/a447e1c604896b7794abc638658b94228121b229/src/README.md#L6)):_
<details><summary>

<i>Previously, pboothe (Peter Boothe) wrote…</i></summary>



> you are either leaving me hanging or being too clever
> </details>
> Oops.  Fixed, and tweaked the others, as well.

---

_[src/tcpinfo_c_adapter.c, line 46 at r1](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15#-KWn1cpmE0k9DYS2IRjB:-KWoCqgGfXyF7bEdDM_K:b-gude08) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/a447e1c604896b7794abc638658b94228121b229/src/tcpinfo_c_adapter.c#L46)):_
<details><summary>

<i>Previously, pboothe (Peter Boothe) wrote…</i></summary>



> Please make this a random number. 123456 is, imo, a worryingly probable input.  Or, put another way: https://vine.co/v/hl7Zpzh1979
> </details>
> Done.  May want to actually make it a sequence number in future.

---

_[src/tcpinfo_c_adapter.c, line 72 at r1](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15#-KWn169D1ba-XMpZaSny:-KWna1kATgnyS9gtrRiG:buug1gj) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/a447e1c604896b7794abc638658b94228121b229/src/tcpinfo_c_adapter.c#L72)):_
<details><summary>

<i>Previously, pboothe (Peter Boothe) wrote…</i></summary>



> ?
> </details>
> Done.  I had some changes in another clone that got left behind.

---

_[src/tcpinfo_lib.cc, line 443 at r1](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15#-KWmzSlfgFuCmRo-kpX8:-KWoCfEcrSpUI7Xcpfur:bt4n9sp) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/a447e1c604896b7794abc638658b94228121b229/src/tcpinfo_lib.cc#L443)):_
<details><summary>

<i>Previously, pboothe (Peter Boothe) wrote…</i></summary>



> Looking into it more: probably not :(
> </details>
> It is a big annoyance, but not a show stopper, so leaving it alone for now.

---

_[src/tcpinfo_lib_test.cc, line 20 at r1](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15#-KWmymQkHfTB9KHov_G5:-KWoCOT4qTCtOQuMjeIy:bz1gpzu) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/a447e1c604896b7794abc638658b94228121b229/src/tcpinfo_lib_test.cc#L20)):_
<details><summary>

<i>Previously, pboothe (Peter Boothe) wrote…</i></summary>



> :(
> 
> This is pretty bad. How hard is it to fix?
> </details>
> Don't know.  It is better than it used to be, but still unsatisfying.  Leaving it as a TODO for now, because I'm not sure what to try next. 

---

_[src/tcpinfo_proto_test.cc, line 534 at r1](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15#-KWmydWFh-PFaPbRgXz1:-KWnb8fsRpC39djwgSxq:b-hqvlmn) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/a447e1c604896b7794abc638658b94228121b229/src/tcpinfo_proto_test.cc#L534)):_
<details><summary>

<i>Previously, pboothe (Peter Boothe) wrote…</i></summary>



> Couldn't this be a method?
> </details>
> Done.  (with a little gymnastics).

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15)_

**Comment by pboothe** [comment]
_[src/tcpinfo_lib_test.cc, line 20 at r1](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15#-KWmymQkHfTB9KHov_G5:-KWoLDG7zka0qwXvklh-:b4wprlf) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/a447e1c604896b7794abc638658b94228121b229/src/tcpinfo_lib_test.cc#L20)):_
<details><summary>

<i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary>



> Don't know.  It is better than it used to be, but still unsatisfying.  Leaving it as a TODO for now, because I'm not sure what to try next. 
> </details>
> Looks like an extern C problem - all the transitive inclusions of "tcpinfo_c_adapter.h" are externed in the code below, except for the ones already included by "connection_cache.h" and "tcpinfo_lib.h".

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15)_

**Comment by pboothe** [comment]
LGTM except for the include-order problem, which if it's not too bad I would strongly prefer fixing. Right now, if I'm right, transitive inclusions are randomly `extern C`-ified or not.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15#-:-KWoLdpkYv5ObWwpOGP4:b4c86xb)_

**Comment by pboothe** [comment]
Reviewed 1 of 3 files at r2.
Review status: 2 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15)_

**Comment by gfr10598** [comment]
I've made vast improvements to the extern "C" stuff.  Main problem was actually a collision with tcpinfo.pb.h declarations of AF_\* colliding with socket.h macros.
Going ahead with submit, but PTAL and let me know if you find any other suggestions.

---

Review status: 2 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15#-:-KWoo3ZyELCCVT22xVBu:b-lmoke)_

**Comment by gfr10598** [comment]
Review status: 2 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/tcpinfo_lib_test.cc, line 20 at r1](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15#-KWmymQkHfTB9KHov_G5:-KWooairMEOM1cEB2TSE:bt2vr1b) ([raw file](https://github.com/m-lab/tcpinfo_lib/blob/a447e1c604896b7794abc638658b94228121b229/src/tcpinfo_lib_test.cc#L20)):_
<details><summary>

<i>Previously, pboothe (Peter Boothe) wrote…</i></summary>



> Looks like an extern C problem - all the transitive inclusions of "tcpinfo_c_adapter.h" are externed in the code below, except for the ones already included by "connection_cache.h" and "tcpinfo_lib.h".
> </details>
> Fixed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/tcpinfo_lib/15)_

**Pull request merged**
